import type { ComponentPanelConfig } from '../../types';

export const FormMeta: ComponentPanelConfig = {
  componentType: 'Form',
  displayName: '表单',
  category: 'form',
  icon: 'edit',
  properties: [
    {
      key: 'name',
      label: '表单名称',
      editor: 'string',
      defaultValue: '',
      group: '基础',
    },
    {
      key: 'initialValues',
      label: '初始值',
      editor: 'json',
      defaultValue: {},
      group: '基础',
    },
    {
      key: 'autoComplete',
      label: '自动完成',
      editor: 'select',
      defaultValue: 'on',
      options: [
        { label: '开启', value: 'on' },
        { label: '关闭', value: 'off' },
      ],
      group: '基础',
    },
    {
      key: 'layout',
      label: '布局',
      editor: 'select',
      defaultValue: 'horizontal',
      options: [
        { label: '水平', value: 'horizontal' },
        { label: '垂直', value: 'vertical' },
        { label: '内联', value: 'inline' },
      ],
      group: '样式',
    },
    {
      key: 'className',
      label: '类名',
      editor: 'string',
      defaultValue: '',
      group: '样式',
    },
    {
      key: 'style',
      label: '样式',
      editor: 'json',
      defaultValue: {},
      group: '样式',
    },
    {
      key: 'labelCol',
      label: '标签布局',
      editor: 'json',
      defaultValue: { span: 6 },
      group: '高级',
      visible: (props) => props.layout !== 'inline',
    },
    {
      key: 'wrapperCol',
      label: '控件布局',
      editor: 'json',
      defaultValue: { span: 18 },
      group: '高级',
      visible: (props) => props.layout !== 'inline',
    },
    {
      key: 'labelAlign',
      label: '标签对齐',
      editor: 'select',
      defaultValue: 'right',
      options: [
        { label: '左', value: 'left' },
        { label: '右', value: 'right' },
      ],
      group: '样式',
    },
    {
      key: 'size',
      label: '尺寸',
      editor: 'select',
      defaultValue: 'middle',
      options: [
        { label: '默认', value: 'middle' },
        { label: '小', value: 'small' },
        { label: '大', value: 'large' },
      ],
      group: '样式',
    },
    {
      key: 'disabled',
      label: '整体禁用',
      editor: 'boolean',
      defaultValue: false,
      group: '高级',
    },
    {
      key: 'preserve',
      label: '保留字段值',
      editor: 'boolean',
      defaultValue: true,
      group: '高级',
    },
    {
      key: 'validateTrigger',
      label: '默认校验触发',
      editor: 'select',
      defaultValue: 'onChange',
      options: [
        { label: '值变更', value: 'onChange' },
        { label: '失焦', value: 'onBlur' },
        { label: '提交', value: 'onSubmit' },
      ],
      group: '高级',
    },
    {
      key: 'validateMessages',
      label: '校验提示模板',
      editor: 'json',
      defaultValue: {},
      group: '高级',
    },
    {
      key: 'requiredMark',
      label: '必填标记',
      editor: 'json',
      defaultValue: true,
      group: '高级',
      description: 'true / false / "optional"',
    },
    {
      key: 'colon',
      label: '显示冒号',
      editor: 'boolean',
      defaultValue: true,
      group: '高级',
      visible: (props) => props.layout !== 'inline',
    },
    {
      key: 'scrollToFirstError',
      label: '提交失败滚动',
      editor: 'boolean',
      defaultValue: false,
      group: '高级',
    },
  ],
};
