import type { ComponentPanelConfig } from '../../types';

export const FormItemMeta: ComponentPanelConfig = {
  componentType: 'FormItem',
  displayName: '表单项',
  category: 'form',
  icon: 'list',
  properties: [
    {
      key: 'label',
      label: '标签',
      editor: 'string',
      defaultValue: '标签',

      group: '基础',
    },
    {
      key: 'name',
      label: '字段名',
      editor: 'string',
      defaultValue: 'field',
      group: '基础',
    },
    {
      key: 'tooltip',
      label: '标签提示',
      editor: 'string',
      defaultValue: '',
      group: '基础',
    },
    {
      key: 'rules',
      label: '校验规则',
      editor: 'formRules',
      defaultValue: [],
      description: '例如 [{ required: true, message: "请输入内容" }]',
      group: '基础',
    },
    {
      key: 'required',
      label: '必填',
      editor: 'boolean',
      defaultValue: false,
      group: '高级',
    },
    {
      key: 'valuePropName',
      label: '值属性名',
      editor: 'string',
      defaultValue: 'value',
      group: '高级',
    },
    {
      key: 'trigger',
      label: '值更新触发',
      editor: 'select',
      defaultValue: 'onChange',
      options: [
        { label: '值变更', value: 'onChange' },
        { label: '失焦', value: 'onBlur' },
      ],
      group: '高级',
    },
    {
      key: 'hasFeedback',
      label: '显示反馈图标',
      editor: 'boolean',
      defaultValue: false,
      group: '高级',
    },
    {
      key: 'validateTrigger',
      label: '校验触发时机',
      editor: 'select',
      defaultValue: 'onChange',
      options: [
        { label: '值变更', value: 'onChange' },
        { label: '失焦', value: 'onBlur' },
        { label: '提交', value: 'onSubmit' },
      ],
      group: '高级',
    },
    {
      key: 'help',
      label: '帮助信息',
      editor: 'string',
      defaultValue: '',
      group: '高级',
    },
    {
      key: 'extra',
      label: '额外说明',
      editor: 'slot',
      defaultValue: '',
      group: '高级',
    },
    {
      key: 'preserve',
      label: '保留字段值',
      editor: 'boolean',
      defaultValue: true,
      group: '高级',
    },
    {
      key: 'hidden',
      label: '隐藏字段',
      editor: 'boolean',
      defaultValue: false,
      group: '高级',
    },
    {
      key: 'noStyle',
      label: '无样式包装',
      editor: 'boolean',
      defaultValue: false,
      group: '高级',
    },
    {
      key: 'validateFirst',
      label: '优先首条报错',
      editor: 'boolean',
      defaultValue: false,
      group: '高级',
    },
    {
      key: 'initialValue',
      label: '字段初始值',
      editor: 'json',
      defaultValue: undefined,
      group: '高级',
    },
    {
      key: 'dependencies',
      label: '依赖字段',
      editor: 'json',
      defaultValue: [],
      group: '高级',
    },
    {
      key: 'labelCol',
      label: '标签布局',
      editor: 'json',
      defaultValue: undefined,
      group: '高级',
    },
    {
      key: 'wrapperCol',
      label: '控件布局',
      editor: 'json',
      defaultValue: undefined,
      group: '高级',
    },
    {
      key: 'className',
      label: '类名',
      editor: 'string',
      defaultValue: '',
      group: '样式',
    },
    {
      key: 'style',
      label: '样式',
      editor: 'json',
      defaultValue: {},
      group: '样式',
    },
  ],
};
