import type { ComponentPanelConfig } from '../../types';

export const TableMeta: ComponentPanelConfig = {
  componentType: 'Table',
  displayName: '表格',
  category: 'display',
  icon: 'table',
  properties: [
    {
      key: 'columns',
      label: '列配置',
      editor: 'tableColumns',
      defaultValue: [{ title: '列1', dataIndex: 'col1', key: 'col1' }],
      group: '基础',
    },
    {
      key: 'dataSource',
      label: '数据源',
      editor: 'json',
      defaultValue: [{ key: '1', col1: '内容1' }],
      group: '基础',
    },
    {
      key: 'rowKey',
      label: '行主键',
      editor: 'string',
      defaultValue: 'key',
      group: '基础',
    },
    {
      key: 'showHeader',
      label: '显示表头',
      editor: 'boolean',
      defaultValue: true,
      group: '基础',
    },
    {
      key: 'size',
      label: '尺寸',
      editor: 'select',
      defaultValue: 'middle',
      options: [
        { label: '默认', value: 'middle' },
        { label: '小', value: 'small' },
        { label: '大', value: 'large' },
      ],
      group: '样式',
    },
    {
      key: 'bordered',
      label: '边框',
      editor: 'boolean',
      defaultValue: false,
      group: '样式',
    },
    {
      key: 'tableLayout',
      label: '布局算法',
      editor: 'select',
      defaultValue: 'auto',
      options: [
        { label: '自动', value: 'auto' },
        { label: '固定', value: 'fixed' },
      ],
      group: '样式',
    },
    {
      key: 'className',
      label: '类名',
      editor: 'string',
      defaultValue: '',
      group: '样式',
    },
    {
      key: 'style',
      label: '样式',
      editor: 'json',
      defaultValue: {},
      group: '样式',
    },
    {
      key: 'pagination',
      label: '分页配置',
      editor: 'json',
      defaultValue: { pageSize: 10, showSizeChanger: true },
      group: '高级',
    },
    {
      key: 'scroll',
      label: '滚动配置',
      editor: 'json',
      defaultValue: {},
      group: '高级',
    },
    {
      key: 'sticky',
      label: '吸顶滚动',
      editor: 'boolean',
      defaultValue: false,
      group: '高级',
    },
    {
      key: 'rowHoverable',
      label: '启用行悬停',
      editor: 'boolean',
      defaultValue: true,
      group: '高级',
    },
    {
      key: 'rowSelection',
      label: '选择配置',
      editor: 'json',
      defaultValue: undefined,
      group: '高级',
      description: '例如 { type: "checkbox" }',
    },
    {
      key: 'loading',
      label: '加载中',
      editor: 'boolean',
      defaultValue: false,
      group: '高级',
    },
  ],
};
