import { antdRuntime } from './runtime';
import type { ComponentManifestRegistry } from '@lowcode-platform/renderer';

const COMMON = [
  'children',
  'className',
  'style',
  'id',
  'title',
  'key',
  'value',
  'initialValue',
] as const;
const TEXT = [
  'strong',
  'type',
  'code',
  'mark',
  'underline',
  'delete',
  'keyboard',
  'ellipsis',
] as const;
const INPUT = [
  'placeholder',
  'type',
  'name',
  'defaultValue',
  'disabled',
  'size',
  'allowClear',
  'maxLength',
  'readOnly',
] as const;

const componentProps: Record<string, readonly string[]> = {
  Page: [],
  Div: [],
  Span: [],
  Container: ['width', 'padding', 'center'],
  Row: ['gutter', 'justify', 'align', 'wrap'],
  Col: ['span', 'offset', 'flex', 'order', 'pull', 'push', 'xs', 'sm', 'md', 'lg', 'xl', 'xxl'],
  Button: ['type', 'name', 'disabled', 'danger', 'block', 'size', 'htmlType', 'loading'],
  Input: [...INPUT, 'bordered'],
  TextArea: [
    'placeholder',
    'name',
    'rows',
    'defaultValue',
    'disabled',
    'maxLength',
    'readOnly',
    'allowClear',
    'autoSize',
  ],
  InputNumber: ['min', 'max', 'step', 'placeholder', 'disabled', 'size'],
  Select: ['options', 'placeholder', 'disabled', 'mode', 'allowClear', 'size'],
  Checkbox: ['checked', 'disabled', 'indeterminate'],
  CheckboxGroup: ['options', 'disabled', 'name', 'defaultValue'],
  Radio: ['checked', 'disabled', 'value'],
  RadioGroup: ['options', 'disabled', 'name', 'buttonStyle', 'defaultValue', 'optionType'],
  RadioButton: ['checked', 'disabled', 'value'],
  Switch: ['checked', 'disabled', 'loading', 'size', 'checkedChildren', 'unCheckedChildren'],
  Slider: ['min', 'max', 'step', 'range', 'marks', 'disabled', 'defaultValue', 'vertical'],
  Form: [
    'layout',
    'initialValues',
    'name',
    'disabled',
    'size',
    'autoComplete',
    'labelCol',
    'wrapperCol',
    'labelAlign',
    'preserve',
    'validateTrigger',
    'validateMessages',
    'requiredMark',
    'colon',
    'scrollToFirstError',
  ],
  FormItem: [
    'name',
    'label',
    'rules',
    'valuePropName',
    'extra',
    'required',
    'tooltip',
    'trigger',
    'hasFeedback',
    'validateTrigger',
    'help',
    'preserve',
    'hidden',
    'noStyle',
    'validateFirst',
    'dependencies',
    'labelCol',
    'wrapperCol',
  ],
  DatePicker: ['placeholder', 'format', 'disabled', 'picker', 'allowClear', 'size', 'showTime'],
  RangePicker: [
    'placeholder',
    'format',
    'disabled',
    'picker',
    'allowClear',
    'size',
    'showTime',
    'separator',
  ],
  Table: [
    'columns',
    'dataSource',
    'rowKey',
    'showHeader',
    'size',
    'bordered',
    'tableLayout',
    'pagination',
    'scroll',
    'sticky',
    'rowHoverable',
    'rowSelection',
    'loading',
  ],
  Card: ['bordered', 'variant', 'cover', 'extra', 'loading', 'size', 'type', 'hoverable'],
  List: ['dataSource', 'renderItem', 'loading', 'size', 'bordered', 'header', 'footer', 'split'],
  ListItem: ['actions', 'extra'],
  Tabs: ['activeKey', 'defaultActiveKey', 'type', 'size', 'centered', 'tabPosition'],
  TabPane: ['tab', 'disabled', 'forceRender', 'closable'],
  Collapse: [
    'activeKey',
    'defaultActiveKey',
    'accordion',
    'bordered',
    'destroyInactivePanel',
    'expandIconPosition',
    'ghost',
  ],
  CollapsePanel: ['header', 'key', 'showArrow', 'disabled', 'collapsible', 'forceRender'],
  Modal: [
    'open',
    'visible',
    'width',
    'footer',
    'closable',
    'maskClosable',
    'title',
    'okText',
    'cancelText',
  ],
  Popover: ['content', 'placement', 'open', 'trigger', 'title'],
  Tooltip: ['title', 'placement', 'open', 'trigger', 'color'],
  Space: ['size', 'direction', 'align', 'wrap'],
  Divider: ['dashed', 'orientation', 'plain', 'type'],
  Layout: ['hasSider'],
  Header: [],
  Content: [],
  Footer: [],
  Sider: ['width', 'collapsed', 'collapsible', 'theme', 'breakpoint', 'collapsedWidth'],
  Typography: [],
  Text: [...TEXT, 'copyable'],
  Title: ['level', ...TEXT, 'copyable'],
  Paragraph: [...TEXT, 'copyable'],
  Tag: ['color', 'closable', 'bordered'],
  Badge: ['count', 'showZero', 'dot', 'status', 'text', 'overflowCount'],
  Alert: ['message', 'description', 'type', 'showIcon', 'closable', 'banner'],
  Steps: ['current', 'items', 'direction', 'size', 'status', 'labelPlacement', 'responsive'],
  Step: ['title', 'description', 'status', 'disabled', 'subTitle'],
  Progress: ['percent', 'status', 'type', 'showInfo', 'strokeColor', 'size'],
  Spin: ['spinning', 'size', 'tip', 'delay'],
  Skeleton: ['active', 'loading', 'avatar', 'paragraph', 'title', 'round'],
  Avatar: ['src', 'size', 'shape', 'alt'],
  Image: ['src', 'alt', 'width', 'height', 'preview'],
  Link: ['href', 'target', 'rel'],
};

function entry(componentType: string, allowedProps: readonly string[]) {
  return Object.freeze({
    componentType,
    allowedProps: Object.freeze([...COMMON, ...allowedProps]),
  });
}

export const antdManifest: ComponentManifestRegistry = Object.freeze(
  Object.fromEntries(
    Object.keys(antdRuntime).map((type) => [type, entry(type, componentProps[type] ?? [])]),
  ),
);
