import type { ComponentPanelConfig } from "@lowcode-platform/types";

export const TypographyMeta: ComponentPanelConfig = {
  componentType: "Typography",
  displayName: "排版",
  category: "typography",
  icon: "typography",
  properties: [
    {
      key: "children",
      label: "内容",
      editor: "string",
      defaultValue: "排版内容",
    },
    {
      key: "variant",
      label: "变体",
      editor: "select",
      defaultValue: "body1",
      options: [
        { label: "标题1", value: "h1" },
        { label: "标题2", value: "h2" },
        { label: "标题3", value: "h3" },
        { label: "标题4", value: "h4" },
        { label: "标题5", value: "h5" },
        { label: "标题6", value: "h6" },
        { label: "正文1", value: "body1" },
        { label: "正文2", value: "body2" },
        { label: "副标题1", value: "subtitle1" },
        { label: "副标题2", value: "subtitle2" },
        { label: "按钮", value: "button" },
        { label: "字幕", value: "caption" },
        { label: "过度标注", value: "overline" },
      ],
    },
    {
      key: "align",
      label: "对齐方式",
      editor: "select",
      defaultValue: "inherit",
      options: [
        { label: "继承", value: "inherit" },
        { label: "左对齐", value: "left" },
        { label: "居中", value: "center" },
        { label: "右对齐", value: "right" },
        { label: "两端对齐", value: "justify" },
      ],
    },
    {
      key: "color",
      label: "颜色",
      editor: "color",
      defaultValue: "#000000",
      group: "样式",
    },
    {
      key: "noWrap",
      label: "不换行",
      editor: "boolean",
      defaultValue: false,
      group: "布局",
    },
    {
      key: "paragraph",
      label: "段落",
      editor: "boolean",
      defaultValue: false,
      group: "布局",
    },
  ],
};
